spring.application.name=placementhub-backend

server.port=9001

jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
jwt.secret=${JWT_SECRET}
google.client-id=${GOOGLE_CLIENT_ID}
googleclientsecret=${GOOGLE_CLIENT_SECRET}